version: '3'
services:
  server:
    container_name: server
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./config/.env.local
    ports:
      - '5000:5000'
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      WAIT_HOSTS: mongodb:27017
    networks:
      - stals-network
  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - ~/mongo:/data/db
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=server_user
      - MONGO_INITDB_ROOT_PASSWORD=server_password
      - MONGO_INITDB_DATABASE=admin
    networks:
      - stals-network
networks:
  stals-network:
    driver: bridge
