const accommodationsActions = {
  ACCOMMODATION_INIT: 'ACCOMMODATION_INIT',
  ACCOMMODATION_CREATE: 'ACCOMMODATION_CREATE',
  ACCOMMODATION_RETRIEVE_ONE: 'ACCOMMODATION_RETRIEVE_ONE',
  ACCOMMODATION_RETRIEVE_ALL: 'ACCOMMODATION_RETRIEVE_ALL',
  ACCOMMODATION_UPDATE: 'ACCOMMODATION_UPDATE',
  ACCOMMODATION_DELETE: 'ACCOMMODATION_DELETE',
}

export default accommodationsActions
